### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by Bunny-push** [Text-to-Audio/AudioLCM#11]
When I use "python scripts/txt2audio_for_lcm.py  --ddim_steps 2 -b configs/audiolcm.yaml --sample_rate 16000 --vocoder-ckpt  vocoder/logs/bigvnat16k93.5w --outdir results --test-dataset audiocaps  -r ckpt/audiolcm.ckpt" to Inference, I get one error: "FileNotFoundError: [Errno 2] No such file or directory: 'audiocaps_mels/test/Y7fmOlUlwoNg_mel.npy'", this file is not open source?And I use "python ldm/data/preprocess/mel_spec.py --tsv_path tmp.tsv" try to generate the melspec file of audio, I get an error: "FileNotFoundError: [Errno 2] No such file or directory: './musiccap.tsv'",this file is also not open source? And can you give an example about the tmp.tsv?

**Comment by liuhuadai** [comment]
Hi, thank you for your attention. I have provided "musiccap.tsv" in our repository for your reference.
