### ISSUE TITLE
Argv Read Error

### ISSUE THREAD

**Issue by NEUMUKI** [Text-to-Audio/AudioLCM#12]
:wave: Hi, It seems like `--tsv_path` doesn't work in mel_spec.py :astonished:, whatever I put in, the path will always be: 
`tsv_path = './musiccap.tsv'` 
I think you'd better to add the `parser.add_argument` function to get the --tsv_path.

**Comment by liuhuadai** [comment]
Hi,
Thanks for pointing that out! I have updated mel_spec.py to use the --tsv_path argument with argparse.
