### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Bunny-push** [Text-to-Audio/AudioLCM#13]
“python main.py --base configs/train/vae.yaml -t --gpus 0,1,2,3,4,5,6,7”   I did not find the configs/train/vae.yaml file

**Comment by liuhuadai** [comment]
Hi, try to use "[autoencoder1d.yaml](https://github.com/Text-to-Audio/AudioLCM/blob/master/configs/autoencoder1d.yaml)".
