### ISSUE TITLE
ldm.data

### ISSUE THREAD

**Issue by slliugit** [Text-to-Audio/AudioLCM#8]
`python ldm/data/preprocess/mel_spec.py --tsv_path tmp.tsv`
May I ask if the data folder in this command is not open source?

**Comment by slliugit** [comment]
I find that the above command seems to be needed for train, but when running the command: `python scripts/txt2audio_for_lcm.py  --ddim_steps 2 -b configs/audiolcm.yaml --sample_rate 16000 --vocoder-ckpt  vocoder/logs/bigvnat16k93.5w --outdir results --test-dataset audiocaps  -r ckpt/audiolcm.ckpt` following Inference with a pre-trained model, I get an error:
`ModuleNotFoundError: No module named 'ldm.data'`

**Comment by liuhuadai** [comment]
I have uploaded the directory.
