### ISSUE TITLE
Inference with pretrained model

### ISSUE THREAD

**Issue by slliugit** [Text-to-Audio/AudioLCM#9]
按照Inference with a pre-trained model部分的指令，遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'audiocaps_mels/test/Y7fmOlUlwoNg_mel.npy'。测试数据的npy和wav文件似乎缺失了。2.之后我尝试按照Dataset preparation生成mel谱，但又出现了FileNotFoundError: [Errno 2] No such file or directory: './musiccap.tsv'。我进一步尝试将报错行的'./musiccap.tsv'改为'/root/autodl-tmp/AudioLCM/audiocaps_test_16000_struct.tsv'，但再次运行后，又出现了TypeError: mel() takes 0 positional arguments but 5 were given。
已经按照您的邮件回复更新了librosa==0.10.2.post1.但是问题没有得到解决

**Comment by liuhuadai** [comment]
It solves for me. You can try with other versions of librosa.-------- 原始邮件 --------发件人： slliu ***@***.***>日期： 2024年6月26日周三 11:09收件人： Text-to-Audio/AudioLCM ***@***.***>抄送： Subscribed ***@***.***>主    题： [Text-to-Audio/AudioLCM] Inference with pretrained model (Issue #9)
按照Inference with a pre-trained model部分的指令，遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'audiocaps_mels/test/Y7fmOlUlwoNg_mel.npy'。测试数据的npy和wav文件似乎缺失了。2.之后我尝试按照Dataset preparation生成mel谱，但又出现了FileNotFoundError: [Errno 2] No such file or directory: './musiccap.tsv'。我进一步尝试将报错行的'./musiccap.tsv'改为'/root/autodl-tmp/AudioLCM/audiocaps_test_16000_struct.tsv'，但再次运行后，又出现了TypeError: mel() takes 0 positional arguments but 5 were given。
已经按照您的邮件回复更新了librosa==0.10.2.post1.但是问题没有得到解决

**Comment by Text-to-Audio** [comment]
> 按照Inference with a pre-trained model部分的指令，遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'audiocaps_mels/test/Y7fmOlUlwoNg_mel.npy'。测试数据的npy和wav文件似乎缺失了。2.之后我尝试按照Dataset preparation生成mel谱，但又出现了FileNotFoundError: [Errno 2] No such file or directory: './musiccap.tsv'。我进一步尝试将报错行的'./musiccap.tsv'改为'/root/autodl-tmp/AudioLCM/audiocaps_test_16000_struct.tsv'，但再次运行后，又出现了TypeError: mel() takes 0 positional arguments but 5 were given。 已经按照您的邮件回复更新了librosa==0.10.2.post1.但是问题没有得到解决



> 按照Inference with a pre-trained model部分的指令，遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'audiocaps_mels/test/Y7fmOlUlwoNg_mel.npy'。测试数据的npy和wav文件似乎缺失了。2.之后我尝试按照Dataset preparation生成mel谱，但又出现了FileNotFoundError: [Errno 2] No such file or directory: './musiccap.tsv'。我进一步尝试将报错行的'./musiccap.tsv'改为'/root/autodl-tmp/AudioLCM/audiocaps_test_16000_struct.tsv'，但再次运行后，又出现了TypeError: mel() takes 0 positional arguments but 5 were given。 已经按照您的邮件回复更新了librosa==0.10.2.post1.但是问题没有得到解决

You can go to https://huggingface.co/spaces/AIGC-Audio/AudioLCM to see the environment configuration
